#!/bin/sh
ssh ubuntu@43.202.2.22 <<EOF
    cd ~/nodeworkspace
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 21.6.0
    npm install
    npm install -g pm2
    pm2 restart ./src/jenkins.config.js
    exit
EOF
